name: breath
description: A set of tools for network gamedev.
version: 0.0.1

environment:
  sdk: ^3.1.1

dependencies:
  shelf: ^1.4.1
  shelf_web_socket: ^1.0.4
  web_socket_channel: ^2.4.0
  oxygen: ^0.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
